### ISSUE TITLE
Good job, a tip for you..

### ISSUE THREAD

**Issue by Seby66** [tecknokitty/FS22-Electro-Pack#1]
Hi. Really good mod! You miss the " xml file axion900TT.xml" (I have clean it in the modDesc for a clean log)
I have a tip if You can add all vehicles in a separate category. It would be a great upgrade to your mod, that to avoid having too many icons in the standard categories.
TY for Your time and for sharing that.

**Comment by tecknokitty** [comment]
yep I accidentally had axion900TT in the mod desc instead of axion960TT thanks for the catch!

as for separate category ill put that on the todo list thanks!
