### ISSUE TITLE
Please admit this mod to modhub.

### ISSUE THREAD

**Issue by DeeDeeRanged** [tecknokitty/FS22-Electro-Pack#2]
As mentioned in the title. I think a lot of people would be interested in this mod comining to the official modhub as console players can than benefit too.

I've been using your mod since december last year and it is great. All my tractors and harvesters are electric now.
Save the environment, thumbs up

**Comment by DeeDeeRanged** [comment]
Also please update the version number in the moddesc.xml to 1.0.4.0 as it is still mentioned 1.0.0

**Comment by tecknokitty** [comment]
updated the modDesc version, 

also posted the mod to modhub, ill see how the approval process goes
